name: Termux to GitHub CPU Shell

on: 
  workflow_dispatch:

jobs:
  run-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup SSH Session via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: Keep Session Alive
        run: |
          echo "SSH session is active. Waiting..."
          while true; do
            sleep 30
          done
